### ISSUE TITLE
Blows up with two consecutive logging statements

### ISSUE THREAD

**Issue by ragurney** [dndungu/log#1]
It seems to have a seg fault if there are two logging statements executed in a row:
```
logger.Info("Oh no!")
logger.Info("Bing!")
```
Result:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10a7e7c]

goroutine 5 [running]:
github.com/zatiti/log.Log.watch(0xc42001e180, 0x0, 0x0)
	/Users/rygurney/go/src/github.com/zatiti/log/log.go:112 +0x5c
created by github.com/zatiti/log.New
	/Users/rygurney/go/src/github.com/zatiti/log/log.go:48 +0xe7
exit status 2
```

**Comment by dndungu** [comment]
Seems you are missing a log writer. You could use `os.Stdout`
```
logger := log.New(os.Stdout)
```

**Comment by dndungu** [comment]
Perhaps this should be set as the default writer.
